export const buttonExamples = {
  "variants": "<script setup lang=\"ts\">\nimport AppButton from '@/components/ui/AppButton.vue'\n</script>\n\n<template>\n  <AppButton>Solid</AppButton>\n  <AppButton variant=\"outline\">Outline</AppButton>\n  <AppButton variant=\"soft\">Soft</AppButton>\n  <AppButton variant=\"ghost\">Ghost</AppButton>\n</template>",
  "colors": "<AppButton color=\"primary\">Guardar</AppButton>\n<AppButton color=\"neutral\">Cancelar</AppButton>\n<AppButton color=\"info\">Información</AppButton>\n<AppButton color=\"success\">Confirmar</AppButton>\n<AppButton color=\"warning\">Revisar</AppButton>\n<AppButton color=\"danger\">Eliminar</AppButton>\n\n<!-- Puedes combinar color y variante. -->\n<AppButton color=\"danger\" variant=\"outline\">Eliminar</AppButton>",
  "states": "<AppButton size=\"sm\">Pequeño</AppButton>\n<AppButton size=\"md\">Mediano</AppButton>\n<AppButton size=\"lg\">Grande</AppButton>\n<AppButton loading>Guardando</AppButton>\n<AppButton disabled>Deshabilitado</AppButton>",
  "icons": "<script setup lang=\"ts\">\nimport { Save, Search } from '@lucide/vue'\nimport AppButton from '@/components/ui/AppButton.vue'\n</script>\n\n<template>\n  <AppButton><Save :size=\"17\" aria-hidden=\"true\" /> Guardar</AppButton>\n  <AppButton icon-only aria-label=\"Buscar\">\n    <Search :size=\"18\" aria-hidden=\"true\" />\n  </AppButton>\n</template>",
  "block": "<AppButton block>Guardar cambios</AppButton>\n<AppButton block variant=\"outline\">Cancelar</AppButton>",
  "groups": "<script setup lang=\"ts\">\nimport AppButton from '@/components/ui/AppButton.vue'\nimport AppButtonGroup from '@/components/ui/AppButtonGroup.vue'\n</script>\n\n<template>\n  <AppButtonGroup label=\"Acciones del registro\">\n    <AppButton variant=\"outline\">Cancelar</AppButton>\n    <AppButton>Guardar</AppButton>\n  </AppButtonGroup>\n</template>",
  "interactive": "<script setup lang=\"ts\">\nimport { ref } from 'vue'\nimport AppButton from '@/components/ui/AppButton.vue'\nimport AppCheckbox from '@/components/ui/AppCheckbox.vue'\n\nconst loading = ref(false)\nconst disabled = ref(false)\nconst clicks = ref(0)\n</script>\n\n<template>\n  <AppCheckbox v-model=\"loading\" label=\"Estado de carga\" />\n  <AppCheckbox v-model=\"disabled\" label=\"Deshabilitado\" />\n  <AppButton :loading=\"loading\" :disabled=\"disabled\" @click=\"clicks++\">\n    {{ loading ? 'Guardando' : 'Probar clic' }}\n  </AppButton>\n  <p role=\"status\">Clics registrados: {{ clicks }}</p>\n</template>"
} as const
