<script setup lang="ts">
import DocsPageHeader from '../components/docs/DocsPageHeader.vue'
import DocsCodeBlock from '../components/docs/DocsCodeBlock.vue'
const typography = [{ label: 'Título principal', classes: 'text-3xl font-semibold' }, { label: 'Título de sección', classes: 'text-2xl font-semibold' }, { label: 'Título de tarjeta', classes: 'text-lg font-medium' }, { label: 'Texto de contenido', classes: 'text-base leading-relaxed' }, { label: 'Texto secundario', classes: 'text-sm text-muted' }, { label: 'Etiqueta auxiliar', classes: 'text-xs font-medium uppercase tracking-wide' }]
const spaces = [ { label: 'gap-2 · 8 px', classes: 'gap-2' }, { label: 'gap-4 · 16 px', classes: 'gap-4' }, { label: 'gap-6 · 24 px', classes: 'gap-6' }, { label: 'gap-8 · 32 px', classes: 'gap-8' } ]
const separators = '<hr class="border-border" />\n<div class="flex items-center gap-4">\n  <hr class="flex-1 border-border" />\n  <span class="text-sm text-muted">O continuar con</span>\n  <hr class="flex-1 border-border" />\n</div>'
</script>
<template>
  <DocsPageHeader eyebrow="Utilidades / Guía visual" title="Utilidades visuales" description="Tipografía, separadores, espaciado y superficies para mantener consistencia en todas las aplicaciones." />
  <section class="component-section"><div class="section-heading"><div><span>01</span><h2>Tipografía</h2></div><p>Poppins y una jerarquía de tamaños compartida.</p></div><div class="showcase-panel space-y-6"><div v-for="item in typography" :key="item.label"><p :class="item.classes">{{ item.label }}</p><code class="text-xs text-muted">{{ item.classes }}</code></div></div></section>
  <section class="component-section"><div class="section-heading"><div><span>02</span><h2>Separadores</h2></div></div><div class="showcase-panel space-y-8"><hr class="border-border" /><hr class="border-border border-dashed" /><div class="flex items-center gap-4"><hr class="flex-1 border-border" /><span class="text-sm text-muted">O continuar con</span><hr class="flex-1 border-border" /></div><div class="flex items-center gap-4"><span>Detalles</span><span class="h-6 border-l border-border" aria-hidden="true"></span><span>Actividad</span></div></div><DocsCodeBlock :code="separators" /></section>
  <section class="component-section"><div class="section-heading"><div><span>03</span><h2>Espaciado</h2></div><p>Usa gap entre elementos y padding dentro de las superficies.</p></div><div class="showcase-panel space-y-6"><div v-for="space in spaces" :key="space.label"><p class="text-sm mb-2">{{ space.label }}</p><div class="flex" :class="space.classes"><span v-for="n in 3" :key="n" class="utility-space-block"></span></div></div></div></section>
  <section class="component-section"><div class="section-heading"><div><span>04</span><h2>Superficies y texto</h2></div></div><div class="grid grid-cols-1 md:grid-cols-3 gap-6"><div class="bg-surface rounded-md border border-border p-6"><strong>Superficie</strong><p class="text-muted mt-2">bg-surface · border-border · rounded-md</p></div><div class="bg-light rounded-md p-6"><strong>Superficie secundaria</strong><p class="text-muted mt-2">bg-light · p-6</p></div><div class="bg-surface rounded-md shadow-card p-6"><strong>Texto truncado</strong><p class="truncate mt-2" title="Descripción muy extensa que se adapta al espacio disponible en la tarjeta">Descripción muy extensa que se adapta al espacio disponible en la tarjeta</p><code class="text-xs text-muted">truncate · shadow-card</code></div></div></section>
</template>
